[theme]
base="dark"
primaryColor="#00ffcc"  
backgroundColor="#0a0f0d" 
secondaryBackgroundColor="#121417"  
textColor="#e0e0e0"  
font="monospace"  
[server]
headless = true
enableCORS = true
port = 8501
